---
title: "Client Report - What's in a Name?"
subtitle: "Unit 1 Task 2"
author: "Jayden Pope"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```

```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pl.read_csv("https://posit.byui.edu/content/0d43d66f-d3b7-4c43-8c36-52e3ed69e7f1/names_year_csv.csv")
```

## QUESTION 1

<!-- Make sure at least one of your charts includes reference marks!! -->

__How does your name at your birth year compare to its use historically? Your must provide a chart. The years labels on your charts should not include a comma.__: 
I was named Jayden in 2006 just before the name peaked in 2009. Though compared to the past 2006 was the highest year of usage to date.


_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
ggplot(df.filter(pl.col("name") == "Jayden"), aes(x="year", y="Total")) + geom_line(color="red", size=1.2) + labs(title="Babies Named Jayden Over Time", x="Year", y ="Total") +scale_x_continuous(format="d")


```


## QUESTION 2

__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__:  
I chose the name Tony for Tony Stark from Iron Man. Iron Man 1 came out in 2008. According to the graph the movie had no impact on the number of people named Tony.

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
ggplot(df.filter(pl.col("name") == "Tony"), aes(x="year", y="Total")) + geom_line(color="red", size=1.2) + labs(title="Babies Named Tony Over Time", x="Year", y ="Total") +scale_x_continuous(format="d")


```

## QUESTION 3

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names in a single chart. What trends do you notice?__:
Martha and Peter have maintained around the same amount of usage throughout the entire time period. While Paul started around the same as Martha and Peter before seeing an uptickin usage just before 1950 lasting until around 1972. Mary stands out as being used significantly more than all other names combined including a significant dip around 1930, a rise at the same time as Paul around 1950, and then an astronomical drop from 1950-1970 where it matches the usage of Paul. All names then continued to decline in their usage overall from 1970 - 2000. 

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
filtered = df.filter((
  (pl.col("name") == "Mary") |
  (pl.col("name") == "Martha") |
  (pl.col("name") == "Peter") |
  (pl.col("name") == "Paul")) & (
  (pl.col("year") >= 1920) &
  (pl.col("year") <= 2000))
  
)
(
  ggplot(filtered, aes(x="year", y="Total", color = "name")) + geom_line(size=1.2) + labs(title="Christian Baby Names Over Time", x="Year", y ="Total") +scale_x_continuous(format="d")
)

```
<!-- Make sure at least one of your charts includes reference marks!! -->