---
title: "Client Report - Flights: Column Aggregation"
subtitle: "Unit 2 Task 2"
author: "Jayden Pope"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import requests #new for reading in JSON
import io       #new for reading in JSON
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
url = "https://raw.githubusercontent.com/byuidatascience/data4missing/master/data-raw/flights_missing/flights_missing.json"
response = requests.get(url)
df = pl.read_json(io.BytesIO(response.content))
```


## QUESTION 1

__Calculate the sample size (i.e. number of rows in the dataset) for each airport in each year__. What do you notice?

While the sample size flucuates up or down a tad on occassion for the most part the sample size stays the same throughout the duration of collected data.

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
row_perport_peryear = df.filter(pl.col("airport_name") != "").group_by("airport_name", "year").len().sort("airport_name", "year")
```

```{python}
row_perport_peryear
```

## QUESTION 2

__Which airport has the worst delays?__ Describe the metric you chose, and why you chose it to determine the “worst” airport. Your answer should include a summary table that lists (for each airport) the total number of flights, total number of delayed flights, proportion of delayed flights, and average delay time in hours. 

I chose the airport that is the "worst" based on the proportion of their flights overall that are delayed and in turn how much the average flight is delayed (I used the total number of flights instead of just the total number of delayed flights to account for the fact that you can't assume a flight won't be delayed for one reason or another) The airport that is the worst is the San Francisco, California Airport. With a total delay proportion of .26 or about 26% of all flights being delayed and an average delay of .27 hours or around a 20 minute delay for any flight.

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
airport_proportions = df.filter(pl.col("airport_name") != "")
```

```{python}
delays_summary = airport_proportions.group_by(["airport_code", "airport_name"]).agg(pl.col("num_of_flights_total").sum(), pl.col("num_of_delays_total").sum(), (pl.col("num_of_delays_total").sum() / pl.col("num_of_flights_total").sum()).alias("delayed_flight_proportion"), (pl.col("minutes_delayed_total").sum() / 60 / pl.col("num_of_flights_total").sum()).alias("average_hours_delayed")).sort(["delayed_flight_proportion", "average_hours_delayed"], descending=True)
```

```{python}
delays_summary
```

## QUESTION 3

__Create a barplot showing the proportion of all flights that are delayed at each airport. Describe what you learn from this graph.__  

This graph not only reaffirms my opinion on the San Francisco, California, airport, but it also shows the margins of difference in delays between each airport. This shows that the Salt Lake City, Utah airport has the least amount of delays proportionally.

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
ggplot(delays_summary) + aes(x="airport_code", y="delayed_flight_proportion") + geom_bar(stat="identity") + labs(title="Proportion of Delays by Airport", x="Airports", y="Proportion of Delayed Flights")
```