---
title: "Client Report - Famous Names"
subtitle: "Unit 1 Task 3"
author: "Jayden Pope"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```

```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pl.read_csv("https://posit.byui.edu/content/0d43d66f-d3b7-4c43-8c36-52e3ed69e7f1/names_year_csv.csv")
```



## QUESTION 1

<!-- Make sure at least one of your charts includes reference marks!! -->

__Make a new column that represents the total number of babies with your name for only those states in which you have lived. (If you have only ever lived in one state, pick at least one other state so you get practice summing across columns). Make a graph displaying that total for your name over time.__

Just like in the previous lesson where my name reached its peak around 2009 the same is true for my name within Washington and Idaho.

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
# Q1
jayden = df.filter(pl.col("name") == "Jayden").with_columns(mystates=pl.col("WA") + pl.col("ID")).select("name", "year", "mystates")

ggplot(jayden, aes(x="year", y="mystates")) +geom_line(size=1.2) + labs(title="Babies Named Jayden In States I've Lived In", x="Year", y="Combined State Total") + scale_x_continuous(format="d")
```


## QUESTION 2

1. __Let's look at a name that is special for members of the church: Brigham. For each year, calculate what proportion of babies named Brigham were born in Idaho and Utah? Make a graph displaying the proportion over time.__  

The proportion of babies named Brigham in Utah in Idaho shot up from 0 starting from 1992 before peaking in 2013 and then rapidly dropping again.

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
# Q2
ldsPortion = df.with_columns(IU=pl.col("UT") + pl.col("ID") / pl.col("Total").sum().over("year")).filter(pl.col("name") == "Brigham").select("name", "year", "IU")

ggplot(ldsPortion, aes(x="year", y="IU")) + geom_line(size=1.2) + labs(title="Proportion of Total Babies Named Brigham\nin Utah and Idaho", x="Year", y="Proportion to Total") + scale_x_continuous(format="d")

```

<!-- Make sure at least one of your charts includes reference marks!! -->

## QUESTION 3

1. __Consider doing some data validation. For the name David, calculate a sum of all 50 states and District of Columbia for each year. Now compare that total to the value in the 'Total' column. In which years, if any, do they not agree?__

The sum of all babies named David in the US and the total given by the data set agree across all years.

_AI use reflection_
**Link** to the original chat:
**The Process** How exactly did you use the tool?
**The Impact**  How did using AI impact your learning?

```{python}
# Q3
states_total = df.filter(pl.col("name") == "David").select("year", st=pl.sum_horizontal(pl.all().exclude("year", "name", "Total"))).sort("year")

total_column = df.filter(pl.col("name") == "David").select("year", "Total").sort("year")

ggplot() + geom_line(data=states_total, mapping=aes(x="year", y="st"), color="blue") + geom_line(data=total_column, mapping=aes(x="year", y="Total"), color="green", linetype="dashed") + labs(title="Babies Named David", x="Year", y="Babies")
```